name: starlorn
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0

  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/cards/Modifiers/
    - assets/cards/Values/
    - assets/animations/


  fonts:
    - family: Bayer-TypeArchiType
      fonts:
        - asset: assets/fonts/Bayer TypeArchiType Regular.otf


    - family: NixieOne
      fonts:
        - asset: assets/fonts/NixieOne-Regular.ttf
