name: starlorn
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0

  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.1
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "starlorn/android/app/src/main/res/mipmap-mdpi/"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "starlorn/android/app/src/main/res/mipmap-mdpi/"
  windows:
    generate: true
    image_path: "starlorn/android/app/src/main/res/mipmap-mdpi/"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "starlorn/android/app/src/main/res/mipmap-mdpi/"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/cards/Modifiers/
    - assets/cards/Values/
    - assets/animations/
    - assets/text/collection.json


  fonts:
    - family: Bayer-TypeArchiType
      fonts:
        - asset: assets/fonts/Bayer TypeArchiType Regular.otf


    - family: NixieOne
      fonts:
        - asset: assets/fonts/NixieOne-Regular.ttf
