name: starlorn
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/bg.png
    - assets/images/bg_play.png
    - assets/cards/1.png
    - assets/cards/2.png
    - assets/cards/3.png
    - assets/cards/4.png
    - assets/cards/5.png
    - assets/cards/6.png
    - assets/cards/7.png
    - assets/cards/8.png
    - assets/cards/9.png
    - assets/cards/cardback.png
    - assets/cards/matched.png
    - assets/cards/Modifiers/Base.png 


  fonts:
    - family: Bayer-TypeArchiType
      fonts:
        - asset: assets/fonts/Bayer TypeArchiType Regular.otf


    - family: NixieOne
      fonts:
        - asset: assets/fonts/NixieOne-Regular.ttf
