// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAluXyZ-l4AW6hxliO5KCOx6KqX-V3mXLs',
    appId: '1:177582481994:web:2b899939fa4569ee99bcb3',
    messagingSenderId: '177582481994',
    projectId: 'starlorn-b41bf',
    authDomain: 'starlorn-b41bf.firebaseapp.com',
    databaseURL: 'https://starlorn-b41bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'starlorn-b41bf.appspot.com',
    measurementId: 'G-1E45XTK42C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdZLvJ72gqmYkmpmp-HTjEbYg99AIgEig',
    appId: '1:177582481994:android:855ad42d54b0cd9299bcb3',
    messagingSenderId: '177582481994',
    projectId: 'starlorn-b41bf',
    databaseURL: 'https://starlorn-b41bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'starlorn-b41bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEwfS0UPXnmnPyO3SVlgx3N19y8bvftLE',
    appId: '1:177582481994:ios:83b1b7e04877dd2399bcb3',
    messagingSenderId: '177582481994',
    projectId: 'starlorn-b41bf',
    databaseURL: 'https://starlorn-b41bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'starlorn-b41bf.appspot.com',
    iosBundleId: 'com.example.starlorn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEwfS0UPXnmnPyO3SVlgx3N19y8bvftLE',
    appId: '1:177582481994:ios:d06ab51ce1a3f12199bcb3',
    messagingSenderId: '177582481994',
    projectId: 'starlorn-b41bf',
    databaseURL: 'https://starlorn-b41bf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'starlorn-b41bf.appspot.com',
    iosBundleId: 'com.example.starlorn.RunnerTests',
  );
}
